baseURL = 'https://subidit.github.io/'
languageCode = 'en-us'
title = 'Subidit Nandy'
summaryLength = 10

[services]
  [services.googleAnalytics]
    ID = 'G-HZ18T84KKG'


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Fonts'
pageRef = '/fonts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30
